=== UoEMainLibrary/archiveslib/public_docs/cataloguing/rules/isaar.dtd
<!--full ISAAR declarations starts here-->

<!ELEMENT isaarcpf (aarheader+, frontmatter+, aar+)>

<!ELEMENT aarheader (aarid+, filedesc+, profiledesc+, revisiondesc+)>
<!ATTLIST aarheader
	audience 	(internal | external) "external"
	langencoding	CDATA	#IMPLIED	
	aarstatus	CDATA	#IMPLIED	
>

<!ELEMENT frontmatter (titlepage)>

<!ELEMENT aar (authcontrolarea+, infoarea+, notearea+)>
<!ATTLIST aar
	type	(person | corporatebody | family) "person"
	id	ID	#REQUIRED
>

<!-- Meta-data...(aarheader) starts here -->

<!ELEMENT aarid (#PCDATA)>
<!ATTLIST aarid
	source	CDATA	#IMPLIED	
	type 	CDATA	#IMPLIED
>

<!ELEMENT filedesc (titlestmt, publicationstmt)>
<!ELEMENT titlestmt (titleproper | subtitle | author)*>

<!ELEMENT titleproper (lb | #PCDATA)*>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>

<!ELEMENT publicationstmt (publisher, address, date)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT address (addressline+)*>
<!ELEMENT addressline (#PCDATA)>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
	type		CDATA		#REQUIRED
	normal		CDATA		#REQUIRED
	certainty	(certain | uncertain)  "certain"
>
<!ELEMENT profiledesc (creation, langusage)>
<!ELEMENT creation (lb | bibref | #PCDATA)>

<!ELEMENT bibref (persname+ | corpname+ | title? | edition? | imprint? | extref+ | #PCDATA)*>

<!ELEMENT persname (#PCDATA)>
<!ATTLIST persname
	source		(ncarules | lcsh)	"ncarules"
	authfilenumber	CDATA			#IMPLIED	
	normal		CDATA			#IMPLIED
	role		CDATA			#IMPLIED
>

<!ELEMENT corpname (#PCDATA)>
<!ATTLIST corpname
	source		(ncarules | lcsh)	"ncarules"
	authfilenumber	CDATA			#IMPLIED	
	normal		CDATA			#IMPLIED
	role		CDATA			#IMPLIED
>

<!ELEMENT list (item+)*>
<!ELEMENT item (date* | #PCDATA)*>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	render	CDATA 	#FIXED	"italic"
	inline	CDATA	#FIXED	"true"
>

<!ELEMENT edition (#PCDATA)>

<!ELEMENT imprint (geogname+ | publisher+ | date+ | #PCDATA)*>
<!ELEMENT geogname (#PCDATA)>
<!ATTLIST geogname
	source		(ncarules | lcsh)	"ncarules"
	othersource    	CDATA			#IMPLIED		
	authfilenumber	CDATA			#REQUIRED	
	normal		CDATA			#REQUIRED
	role		CDATA			#IMPLIED
>

<!ELEMENT extref (#PCDATA)>
<!ATTLIST extref
	href	CDATA	#IMPLIED
	inline	CDATA	#FIXED 	"true"
>


<!ELEMENT langusage (language)>
<!ELEMENT language (#PCDATA)>

<!ELEMENT revisiondesc (list)>

<!-- Front Matter declarations starts here-->

<!ELEMENT titlepage (titleproper, subtitle, author, publisher, date)>



<!-- element list for the Authority Record starts here-->

<!ELEMENT authcontrolarea (head, unitid, authentry)>
<!ATTLIST authcontrolarea  
	encodinganalog CDATA #IMPLIED
>

<!ELEMENT infoarea (head, occsphere, relships, otherinfo, honqual)>
<!ATTLIST infoarea 
	encodinganalog CDATA #IMPLIED
>

<!ELEMENT notearea (archnote, rules, creationdate)>
<!ATTLIST notearea 
	encodinganalog CDATA #IMPLIED
>

<!-- element list for authority control area -->

<!ELEMENT head (#PCDATA)>

<!ELEMENT unitid (#PCDATA)>
<!ATTLIST unitid
	label		CDATA 	#IMPLIED
	encodinganalog	CDATA	#IMPLIED
	type		CDATA	#IMPLIED
	countrycode	CDATA	#FIXED	"GB"
	repositorycode	CDATA	#IMPLIED
	audience	(internal | external) "external"
>		

<!ELEMENT authentry (#PCDATA)>
<!ATTLIST authentry
	label		CDATA 	#IMPLIED
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
	authfilenumber 	CDATA	#REQUIRED
	normal		CDATA	#REQUIRED
	href		CDATA 	#IMPLIED
>

<!-- element list for information area -->

<!ELEMENT occsphere (head, p+)>
<!ATTLIST occsphere
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
> 

<!ELEMENT p (bibref* | date* | persname* | corpname* | geogname* | list* | #PCDATA)*>

<!ELEMENT relships (head, p+)>
<!ATTLIST relships
	encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>
<!ELEMENT otherinfo (head, p+)>
<!ATTLIST otherinfo
encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

<!ELEMENT honqual (head, p+)>
<!ATTLIST honqual
	encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>
<!-- element list for the note area -->

<!ELEMENT archnote (head, p+)>
<!ATTLIST archnote 
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
> 

<!ELEMENT rules (head, p+)>
<!ATTLIST rules
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

<!ELEMENT creationdate (p | persname | date | #PCDATA)*>
<!ATTLIST creationdate
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

=== UoEMainLibrary/archiveslib/source_docs/isaar/murchison.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE isaarcpf SYSTEM "isaar.dtd">
<isaarcpf> 
  <aarheader audience="internal" langencoding="ISO 639"
	aarstatus="edited-full-draft"> 
	 <aarid source="GB-0237" type="FPI"> "-//Edinburgh University Library
		Special Collections Division :: Archival Authority Records//DOCUMENT GB-0237-
		NAHSTE-P0179-20020129 //EN" </aarid> 
	 <filedesc> 
		<titlestmt> 
		  <titleproper>GB 0237 NAHSTE P0179</titleproper> 
		  <subtitle>Murchison | Sir | Roderick Impey | 1792-1871 | baronet |
			 professor of geology, University of Edinburgh</subtitle> 
		  <author>Compiled for the NAHSTE project by Andrew Thomson, Edinburgh
			 University Library Special Collections Division, 29 January 2002</author> 
		</titlestmt> 
		<publicationstmt> 
		  <publisher>Edinburgh University Library Special Collections
			 Division</publisher> 
		  <address> 
			 <addressline>The University of Edinburgh</addressline> 
			 <addressline>George Square</addressline> 
			 <addressline>Edinburgh EH8 9LJ</addressline> 
			 <addressline>Scotland</addressline> 
			 <addressline>United Kingdom</addressline> 
		  </address> 
		  <date type="single" normal="20020129">29 January 2002</date> 
		</publicationstmt> 
	 </filedesc> 
	 <profiledesc> 
		<creation>XML generated using the ISAAR(CPF) DTD and XMetal template
		  prepared, as part of the NAHSTE project, in collaboration with the GASHE
		  project, by Sarah Higgins, Edinburgh University Library Special Collections
		  Division, 2001, with assistance from Pete Johnston, Lesley Richmond and Moira
		  Rankin, Glasgow University Archive Services. </creation> 
		<langusage> 
		  <language>EN</language> 
		</langusage> 
	 </profiledesc> 
	 <revisiondesc> 
		<list> 
		  <item>No revisions to date</item> 
		</list> 
	 </revisiondesc> 
  </aarheader> 
  <frontmatter> 
	 <titlepage> 
		<titleproper>GB 0237 NAHSTE P0179</titleproper> 
		<subtitle>Murchison | Sir | Roderick Impey | 1792-1871| baronet |
		  professor of geology, University of Edinburgh</subtitle> 
		<author>Compiled for the NAHSTE project by Andrew Thomson , Edinburgh
		  University Library Special Collections Division, 29 January 2002</author> 
		<publisher>Edinburgh University Library Special Collections
		  Division</publisher> 
		<date type="single" normal="20020129">29 January 2002</date> 
	 </titlepage> 
  </frontmatter> 
  <aar id="GB-0237-NAHSTE-P0179"> 
	 <authcontrolarea> 
		<head>AUTHORITY CONTROL AREA</head> 
		<unitid label="Identity Code" encodinganalog="isaar11" type="NAHSTE"
		 repositorycode="0237">GB 0237 NAHSTE P0179</unitid> 
		<authentry encodinganalog="isaar13" label="Authority Entry"
		 authfilenumber="GB 0237 NAHSTE P0179" normal="Gregory, David">Murchison | Sir |
		  Roderick Impey | 1792-1871| baronet | professor of geology, University of
		  Edinburgh</authentry> 
	 </authcontrolarea> 
	 <infoarea encodinganalog="isaar2"> 
		<head>INFORMATION AREA</head> 
		<occsphere encodinganalog="isaar226"> 
		  <head>Occupation, Sphere of Activity</head> 
		  <p>Sir Roderick Impey Murchison was born into a wealthy Highland
			 family. He was sent to military college and fought in the Peninsular War. Once
			 he had given up his passion for fox-hunting (he became one of the greatest fox
			 hunters in the midland counties), Murchison, at the age of 32, turned his
			 attention to science, devoting the rest of his life to geology. Sir Humphrey
			 Davy persuaded him to attend lectures at the Royal Institution. He also joined
			 the Geological Society of London, where he gave his first paper in 
			 <date normal="1825" type="single">1825</date>. Between 
			 <date normal="1825/1831" type="inclusive">1825-1831</date> Murchison
			 explored large parts of England, Scotland and France accumulating material for
			 three of his own memoirs, as well as two more written in conjunction with Adam
			 Sedgwick. </p> 
		  <p>In 
			 <date normal="1831" type="single">1831</date> at the suggestion of
			 William Buckland, he travelled to South Wales and the Welsh Borderland, where
			 he conducted research into the mass of rocks known as 'greywacke' rocks,
			 underlying the Old Red Sandstone. Murchison produced a sequence of the rocks
			 and the fossils contained within them, and these results were ultimately pulled
			 together to form his great work of 
			 <date normal="1839" type="publication">1839</date>,
			 <bibref><title>The Silurian System</title></bibref>. The establishment of the
			 silurian system was followed a year later by that of the Devonian System,
			 founded along with Alan Sedgwick. </p> 
		  <p>Murchison then went on expedition to Russia, Scandinavia and
			 Finland, and collaborated with Von Keyserling and De Verneuil in The Geology of
			 Russia and the Ural Mountains (<date normal="1845" type="single">1845</date>).
			 In 
			 <date normal="1841" type="single">1841</date> he proposed the
			 establishment of the Permian System, based upon his Russian explorations. In 
			 <date normal="1855" type="appointmentdate">1855</date> he succeeded
			 Sir Henry de la Beche as Director-General of the Geological Survey, the most
			 important official post in British geology. Murchison eventually endowed by
			 bequest the Society's second highest award, the Murchison Medal, and had helped
			 to establish the Murchison Professorship of Geology at the University of
			 Edinburgh.</p> 
		</occsphere> 
		<relships encodinganalog="isaar228"> 
		  <head>Relationships</head> 
		  <p>None</p> 
		</relships> 
		<otherinfo encodinganalog="isaar229"> 
		  <head>Other Significant Information</head> 
		  <p>Notable publications:</p> 
		  <p><bibref><title>The Silurian System</title>, (<imprint><date
			 type="publication" normal="1839"
			 certainty="certain">1839</date>)</imprint></bibref> </p> 
		  <p><bibref><title>The Geology of Russia and the Ural Mountains</title>,
			 ( <imprint><date type="publication" normal="1845"
			 certainty="certain">1845</date>)</imprint></bibref> </p> 
		</otherinfo> 
		<honqual encodinganalog="nahste2210"> 
		  <head>Honours, Qualifications and Appointments</head> 
		  <p><date type="appointmentdate" normal="1826">1826</date>: Elected
			 Fellow, Royal Society (FRS)</p> 
		  <p><date type="appointmentdate" normal="1831">1831</date>: Appointed
			 President, Geological Society of London</p> 
		  <p><date type="appointmentdate" normal="1842/1843">1842-1843</date>:
			 Appointed President, Geological Society of London</p> 
		  <p><date type="appointmentdate" normal="1843">1843</date>: Appointed
			 President, Royal Geographical Society of London</p> 
		  <p><date type="appointmentdate" normal="1846">1846</date>: Created
			 Knight Commander, Order of the Bath (KCB)</p> 
		  <p><date type="appointmentdate" normal="1846">1846</date>: Appointed
			 President, British Association</p> 
		  <p><date type="appointmentdate" normal="1855">1855</date>: Appointed
			 Director-General, Geological Survey</p> 
		  <p><date type="single" normal="1864">1864</date>: Awarded Wollaston
			 Medal of the Geological Society</p> 
		  <p><date type="single" normal="1866">1866</date>: Created Baronet</p> 
		</honqual> 
	 </infoarea> 
	 <notearea encodinganalog="ISAAR3"> 
		<archnote encodinganalog="isaar31"> 
		  <head>Notes</head> 
		  <p>List of sources for the biographical information:</p> 
		  <p> <bibref>
			 <persname source="ncarules" normal="Gillispie, Charles C"
			 role="editor">Gillispie, Charles C</persname>, <title
			 render="italic">Dictionary of scientific biography, vol vii</title>, (<imprint>
			 <geogname source="lcsh" authfilenumber="483"
			 normal="New York (N.Y.), United States">New York </geogname>, 
			 <publisher>Scribner's</publisher>, 
			 <date type="publication" normal="1972"
			  certainty="certain">1972</date>)</imprint></bibref></p> 
		  <p> <bibref><title render="italic">Lefalophodon, A history of
			 evolutionary biology website</title>, (
			 <extref
			  href="http://www.nceas.ucsb.edu/~alroy/lefa/Murchison.html">http://www.nceas.ucsb.edu/~alroy/lefa/Murchison.html</extref>
			 <imprint>, 
			 <date type="publication" normal="1990/1999"
			  certainty="uncertain">1990s</date>)</imprint></bibref></p> 
		  <p> <bibref><title render="italic">Encyclopaedia Britannica, vol
			 15</title>, (<imprint>
			 <geogname source="lcsh" authfilenumber="502"
			  normal="Chicago (Illinois), United States">Chicago</geogname>, 
			 <publisher>William Benton</publisher>, 
			 <date type="publication" normal="1964"
			  certainty="certain">1964</date>)</imprint></bibref></p> 
		</archnote> 
		<rules encodinganalog="isaar32"> 
		  <head>Rules or Conventions</head> 
		  <p>Authority record created according to the<bibref><corpname
			 normal="National Council on Archives">National Council on
			 Archives</corpname><title>Rules for the Construction of Personal, Place and
			 Corporate Names (NCA Rules)</title><imprint> 
			 <date type="publication" normal="1997">1997</date></imprint></bibref>
			 and <bibref><corpname normal="International Council on Archives">International
			 Council on Archives: Ad Hoc Committee on Descriptive
			 Standards</corpname><title>International Standard Archival Authority Record for
			 Corporate Bodies, Persona and Families (ISAAR)CPF</title><imprint> 
			 <date type="publication"
			  normal="1995">1995</date></imprint></bibref></p> 
		</rules> 
		<creationdate encodinganalog="isaar33"> 
		  <p>Personal name authority record compiled for the NAHSTE project by
			 <persname role="archivist" normal="Thomson, Andrew">Andrew Thomson</persname>,
			 Edinburgh University Library Special Collections Division, 
			 <date type="single" normal="20020129">29 January
				2002</date></p></creationdate> 
	 </notearea> 
  </aar>
</isaarcpf>

=== UoEMainLibrary/archiveslib/source_docs/isaar/FARMER.XML
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE isaarcpf SYSTEM "isaar.dtd">
<isaarcpf> 
  <aarheader audience="internal" langencoding="ISO 639"
	aarstatus="edited-full-draft"> 
	 <aarid source="GB-0237" type="FPI"> "-//Edinburgh University Library
		Special Collections Division :: Archival Authority Records//DOCUMENT
		GB-0237-NAHSTE-P0588 20020515 //EN" </aarid> 
	 <filedesc> 
		<titlestmt> 
		  <titleproper>GB 0237 NAHSTE P0588</titleproper> 
		  <subtitle>Farmer | Sir | John Bretland | 1865-1944 | professor,
			 Imperial College of Science and Technology, London (England)</subtitle> 
		  <author>Compiled for the NAHSTE project by Olivier Usher, Edinburgh
			 University Library Special Collections Division, 15 April 2002</author> 
		</titlestmt> 
		<publicationstmt> 
		  <publisher>Edinburgh University Library Special Collections
			 Division</publisher> 
		  <address> 
			 <addressline>The University of Edinburgh</addressline> 
			 <addressline>George Square</addressline> 
			 <addressline>Edinburgh EH8 9LJ</addressline> 
			 <addressline>Scotland</addressline> 
			 <addressline>United Kingdom</addressline> 
		  </address> 
		  <date type="single" normal="20020415">15 April 2002</date> 
		</publicationstmt> 
	 </filedesc> 
	 <profiledesc> 
		<creation>XML generated using the ISAAR(CPF) DTD and XMetal template
		  prepared, as part of the NAHSTE project, in collaboration with the GASHE
		  project, by Sarah Higgins, Edinburgh University Library Special Collections
		  Division, 2001, with assistance from Pete Johnston, Lesley Richmond and Moira
		  Rankin, Glasgow University Archive Services. </creation> 
		<langusage> 
		  <language>EN</language> 
		</langusage> 
	 </profiledesc> 
	 <revisiondesc> 
		<list> 
		  <item>No revisions to date</item> 
		</list> 
	 </revisiondesc> 
  </aarheader> 
  <frontmatter> 
	 <titlepage> 
		<titleproper>GB 0237 NAHSTE P0588</titleproper> 
		<subtitle>Farmer | Sir | John Bretland | 1865-1944 | professor, Imperial
		  College of Science and Technology, London (England)</subtitle> 
		<author>Compiled for the NAHSTE project by Olivier Usher, Edinburgh
		  University Library Special Collections Division, 15 April 2002</author> 
		<publisher>Edinburgh University Library Special Collections Division
		  </publisher> 
		<date type="single" normal="20020415">15 April 2002</date> 
	 </titlepage> 
  </frontmatter> 
  <aar id="GB-0237-NAHSTE-P0588"> 
	 <authcontrolarea> 
		<head>AUTHORITY CONTROL AREA</head> 
		<unitid label="Identity Code" encodinganalog="isaar11" type="NAHSTE"
		 repositorycode="0237">GB 0237 NAHSTE P0588</unitid> 
		<authentry encodinganalog="isaar13" label="Authority Entry"
		 authfilenumber="GB 0237 NAHSTE P0588"
		 normal="Farmer, Sir, John Bretland">Farmer | Sir | John Bretland | 1865-1944 |
		  professor, Imperial College of Science and Technology, London
		  (England)</authentry> 
	 </authcontrolarea> 
	 <infoarea encodinganalog="isaar2"> 
		<head>INFORMATION AREA</head> 
		<occsphere encodinganalog="isaar226"> 
		  <head>Occupation, Sphere of Activity</head> 
		  <p>Sir John Bretland Farmer (<date type="life-span"
			 normal="1865/1944">1865-1944</date>) was an important botanist at the Royal
			 College of Science (now Imperial College, London) who pioneered the teaching of
			 skills useful for applied botany in the British colonies, transformed his
			 university department and was responsible for a number of scientific studies
			 into chromosomes, cancer and plant physiology.</p> 
		  <p>While studying at Magdalen College, Oxford, Farmer was influenced by
			 Isaac Bayley Balfour (<date type="life-span"
			 normal="1853/1922">1853-1922</date>), who was at the time the Sherardian
			 professor of botany. Balfour encouraged Farmer to concentrate on botany, which
			 he did. He graduated with first class honours in Natural Science in 
			 <date type="single" normal="1883">1883</date>.</p> 
		  <p>A formative experience in Farmer's life was his trip to Ceylon (now
			 Sri Lanka). During this journey, in which he gained experience of the
			 agricultural systems in use in the colonies, and the problems faced by mass
			 agriculture in a tropical climate, he became convinced of the necessity of
			 teaching students the practical details of botany, as well as the theoretical
			 approach, so that they could be of use to this industry. When he took charge of
			 the botany section at the Royal College of Science, he became the first to
			 teach in this unconventional manner.</p> 
		  <p>Among the subjects discussed in his publications were cancerous
			 tissues. Farmer argued that cancerous tissue was made up of cells that had
			 developed into "gametoid" form - they had taken on characteristics of
			 reproductive (gametogenic) cells. Another of his publications reported an
			 experiment he had conducted which showed that certain oxygen-requiring
			 biological processes in plants could continue without an external source of
			 oxygen, providing they were illuminated. This he explained by the production in
			 the plants by respiration of oxygen from carbon dioxide. In other works, Farmer
			 coined the terms 'meiosis' and 'meiotic', investigated wood's ability to
			 conduct water and disproved (in association with Miss L. Digby a theory
			 relating the size of chromosomes with the type of animal. </p> 
		  <p>Farmer was appointed by the government to investigate the workings
			 of the agriculture departments of Britain's non self-governing colonies. The
			 recommendations he made, based in part on his experiences of Ceylon and his
			 experience as professor of botany, made a considerable impact on the
			 agricultural techniques of these territories.</p> 
		</occsphere> 
		<relships encodinganalog="isaar228"> 
		  <head>Relationships</head> 
		  <p>Sir John Bretland Farmer was influenced while at university by Isaac
			 Bayley Balfour (<date type="life-span" normal="1853/1922">1853-1922</date>)</p>
		  
		</relships> 
		<otherinfo encodinganalog="isaar229"> 
		  <head>Other Significant Information</head> 
		  <p>None</p> 
		</otherinfo> 
		<honqual encodinganalog="nahste2210"> 
		  <head>Honours, Qualifications and Appointments</head> 
		  <p><date type="single" normal="1883">1883</date>: Awarded First Class
			 Degree, Magdalen College, Oxford</p> 
		  <p><date type="appointmentdate" normal="1892">1892</date>: Appointed
			 Assistant-Professor of Botany, Royal College of Science</p> 
		  <p><date type="appointmentdate" normal="1895">1895</date>: Appointed
			 Professor of Botany, Royal College of Science</p> 
		  <p><date type="appointmentdate" normal="1900">1900</date>: Elected
			 Fellow of the Royal Society</p> 
		  <p><date type="single" normal="1919">1919</date>: Awarded Royal Medal
			 of the Royal Society</p> 
		  <p><date type="appointmentspan" normal="1919/1921">1919-1921</date>:
			 Elected Vice-President of the Royal Society</p> 
		  <p><date type="single" normal="1926">1926</date>: Awarded
			 Knighthood</p> 
		</honqual> 
	 </infoarea> 
	 <notearea encodinganalog="ISAAR3"> 
		<archnote encodinganalog="isaar31"> 
		  <head>Notes</head> 
		  <p>List of sources for the biographical information:</p> 
		  <p><bibref><corpname normal="Royal Society" role="editor">Royal
			 Society</corpname>, <title>Obituary Notices of Fellows of the Royal Society
			 1945-1948</title>, (<imprint><geogname source="lcsh" authfilenumber="530"
			 normal="London (England)">London</geogname>, 
			 <publisher>Royal Society</publisher>, 
			 <date type="publication" normal="1943/1953"
			 certainty="uncertain">c1948</date>)</imprint></bibref></p> 
		  <p> <bibref> <title>Concise Dictionary of National Biography</title>, (
			 <imprint><geogname source="lcsh" authfilenumber="532"
			 normal="London (England)">London (England)</geogname>, 
			 <publisher>Oxford University Press</publisher>, 
			 <date type="publication" normal="1992"
			 certainty="certain">1992</date>)</imprint></bibref></p> 
		  <p><bibref><persname source="ncarules" normal="Black, Adam"
			 role="editor">Black, Adam</persname>,
			 <persname source="ncarules" normal="Black, Charles" role="editor">Black,
			 Charles</persname>, <title>Who Was Who 1941-1950</title>, (<imprint><geogname
			 source="lcsh" authfilenumber="530" normal="London (England)">London</geogname>,
			 
			 <publisher>A &amp; C Black</publisher>, 
			 <date type="publication" normal="1952"
			 certainty="certain">1952</date>)</imprint></bibref></p> 
		</archnote> 
		<rules encodinganalog="isaar32"> 
		  <head>Rules or Conventions</head> 
		  <p>Authority record created according to the <bibref>
			 <corpname normal="National Council on Archives">National Council on
			 Archives</corpname> <title>Rules for the Construction of Personal, Place and
			 Corporate Names (NCA Rules)</title> <imprint> 
			 <date type="publication" normal="1997">1997</date></imprint></bibref>
			 and <bibref> <corpname normal="International Council on Archives">International
			 Council on Archives: Ad Hoc Committee on Descriptive Standards</corpname>
			 <title>International Standard Archival Authority Record for Corporate Bodies,
			 Persons and Families (ISAAR)CPF</title> <imprint> 
			 <date type="publication"
			 normal="1995">1995</date></imprint></bibref></p> 
		</rules> 
		<creationdate encodinganalog="isaar33"> 
		  <p>Personal name authority record compiled for the NAHSTE project by
			 <persname role="archivist" normal="Usher, Olivier">Olivier Usher</persname>,
			 Edinburgh University Library Special Collections Division, 
			 <date type="single" normal="20020415">15 April
				2002</date></p></creationdate> 
	 </notearea> 
  </aar>
</isaarcpf>
