=== UoEMainLibrary/archiveslib/public_docs/cataloguing/rules/isaar.dtd
<!--full ISAAR declarations starts here-->

<!ELEMENT isaarcpf (aarheader+, frontmatter+, aar+)>

<!ELEMENT aarheader (aarid+, filedesc+, profiledesc+, revisiondesc+)>
<!ATTLIST aarheader
	audience 	(internal | external) "external"
	langencoding	CDATA	#IMPLIED	
	aarstatus	CDATA	#IMPLIED	
>

<!ELEMENT frontmatter (titlepage)>

<!ELEMENT aar (authcontrolarea+, infoarea+, notearea+)>
<!ATTLIST aar
	type	(person | corporatebody | family) "person"
	id	ID	#REQUIRED
>

<!-- Meta-data...(aarheader) starts here -->

<!ELEMENT aarid (#PCDATA)>
<!ATTLIST aarid
	source	CDATA	#IMPLIED	
	type 	CDATA	#IMPLIED
>

<!ELEMENT filedesc (titlestmt, publicationstmt)>
<!ELEMENT titlestmt (titleproper | subtitle | author)*>

<!ELEMENT titleproper (lb | #PCDATA)*>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT author (#PCDATA)>

<!ELEMENT publicationstmt (publisher, address, date)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT address (addressline+)*>
<!ELEMENT addressline (#PCDATA)>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
	type		CDATA		#REQUIRED
	normal		CDATA		#REQUIRED
	certainty	(certain | uncertain)  "certain"
>
<!ELEMENT profiledesc (creation, langusage)>
<!ELEMENT creation (lb | bibref | #PCDATA)>

<!ELEMENT bibref (persname+ | corpname+ | title? | edition? | imprint? | extref+ | #PCDATA)*>

<!ELEMENT persname (#PCDATA)>
<!ATTLIST persname
	source		(ncarules | lcsh)	"ncarules"
	authfilenumber	CDATA			#IMPLIED	
	normal		CDATA			#IMPLIED
	role		CDATA			#IMPLIED
>

<!ELEMENT corpname (#PCDATA)>
<!ATTLIST corpname
	source		(ncarules | lcsh)	"ncarules"
	authfilenumber	CDATA			#IMPLIED	
	normal		CDATA			#IMPLIED
	role		CDATA			#IMPLIED
>

<!ELEMENT list (item+)*>
<!ELEMENT item (date* | #PCDATA)*>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	render	CDATA 	#FIXED	"italic"
	inline	CDATA	#FIXED	"true"
>

<!ELEMENT edition (#PCDATA)>

<!ELEMENT imprint (geogname+ | publisher+ | date+ | #PCDATA)*>
<!ELEMENT geogname (#PCDATA)>
<!ATTLIST geogname
	source		(ncarules | lcsh)	"ncarules"
	othersource    	CDATA			#IMPLIED		
	authfilenumber	CDATA			#REQUIRED	
	normal		CDATA			#REQUIRED
	role		CDATA			#IMPLIED
>

<!ELEMENT extref (#PCDATA)>
<!ATTLIST extref
	href	CDATA	#IMPLIED
	inline	CDATA	#FIXED 	"true"
>


<!ELEMENT langusage (language)>
<!ELEMENT language (#PCDATA)>

<!ELEMENT revisiondesc (list)>

<!-- Front Matter declarations starts here-->

<!ELEMENT titlepage (titleproper, subtitle, author, publisher, date)>



<!-- element list for the Authority Record starts here-->

<!ELEMENT authcontrolarea (head, unitid, authentry)>
<!ATTLIST authcontrolarea  
	encodinganalog CDATA #IMPLIED
>

<!ELEMENT infoarea (head, occsphere, relships, otherinfo, honqual)>
<!ATTLIST infoarea 
	encodinganalog CDATA #IMPLIED
>

<!ELEMENT notearea (archnote, rules, creationdate)>
<!ATTLIST notearea 
	encodinganalog CDATA #IMPLIED
>

<!-- element list for authority control area -->

<!ELEMENT head (#PCDATA)>

<!ELEMENT unitid (#PCDATA)>
<!ATTLIST unitid
	label		CDATA 	#IMPLIED
	encodinganalog	CDATA	#IMPLIED
	type		CDATA	#IMPLIED
	countrycode	CDATA	#FIXED	"GB"
	repositorycode	CDATA	#IMPLIED
	audience	(internal | external) "external"
>		

<!ELEMENT authentry (#PCDATA)>
<!ATTLIST authentry
	label		CDATA 	#IMPLIED
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
	authfilenumber 	CDATA	#REQUIRED
	normal		CDATA	#REQUIRED
	href		CDATA 	#IMPLIED
>

<!-- element list for information area -->

<!ELEMENT occsphere (head, p+)>
<!ATTLIST occsphere
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
> 

<!ELEMENT p (bibref* | date* | persname* | corpname* | geogname* | list* | #PCDATA)*>

<!ELEMENT relships (head, p+)>
<!ATTLIST relships
	encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>
<!ELEMENT otherinfo (head, p+)>
<!ATTLIST otherinfo
encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

<!ELEMENT honqual (head, p+)>
<!ATTLIST honqual
	encodinganalog 	CDATA	#IMPLIED
	audience	(internal | external) "external"
>
<!-- element list for the note area -->

<!ELEMENT archnote (head, p+)>
<!ATTLIST archnote 
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
> 

<!ELEMENT rules (head, p+)>
<!ATTLIST rules
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

<!ELEMENT creationdate (p | persname | date | #PCDATA)*>
<!ATTLIST creationdate
	encodinganalog	CDATA	#IMPLIED
	audience	(internal | external) "external"
>

=== UoEMainLibrary/archiveslib/source_docs/isaar/ROMANES.XML
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE isaarcpf SYSTEM "isaar.dtd">
<isaarcpf> 
  <aarheader audience="internal" langencoding="ISO 639"
	aarstatus="edited-full-draft"> 
	 <aarid source="GB-0237" type="FPI"> "-//Edinburgh University Library
		Special Collections Division :: Archival Authority Records//DOCUMENT
		GB-0237-NAHSTE-P0694 20020405 //EN" </aarid> 
	 <filedesc> 
		<titlestmt> 
		  <titleproper>GB 0237 NAHSTE P0694</titleproper> 
		  <subtitle>Romanes | George John | 1848-1894 | biologist</subtitle> 
		  <author>Compiled for the NAHSTE project by Olivier Usher , Edinburgh
			 University Library Department of Special Collections, 05 April 2002</author> 
		</titlestmt> 
		<publicationstmt> 
		  <publisher>Edinburgh University Library Special Collections
			 Division</publisher> 
		  <address> 
			 <addressline>The University of Edinburgh</addressline> 
			 <addressline>George Square</addressline> 
			 <addressline>Edinburgh EH8 9LJ</addressline> 
			 <addressline>Scotland</addressline> 
			 <addressline>United Kingdom</addressline> 
		  </address> 
		  <date type="single" normal="20020405">05 April 2002</date> 
		</publicationstmt> 
	 </filedesc> 
	 <profiledesc> 
		<creation>XML generated using the ISAAR(CPF) DTD and XMetal template
		  prepared, as part of the NAHSTE project, in collaboration with the GASHE
		  project, by Sarah Higgins, Edinburgh University Library Special Collections
		  Division, 2001, with assistance from Pete Johnston, Lesley Richmond and Moira
		  Rankin, Glasgow University Archive Services. </creation> 
		<langusage> 
		  <language>EN</language> 
		</langusage> 
	 </profiledesc> 
	 <revisiondesc> 
		<list> 
		  <item>No revisions to date</item> 
		</list> 
	 </revisiondesc> 
  </aarheader> 
  <frontmatter> 
	 <titlepage> 
		<titleproper>GB 0237 NAHSTE P0694</titleproper> 
		<subtitle>Romanes | George John | 1848-1894 | biologist</subtitle> 
		<author>Compiled for the NAHSTE project by Olivier Usher , Edinburgh
		  University Library Special Collections Division, 05 April 2002</author> 
		<publisher>Edinburgh University Library Department of Special
		  Collections</publisher> 
		<date type="single" normal="20020405">05 April 2002</date> 
	 </titlepage> 
  </frontmatter> 
  <aar id="GB-0237-NAHSTE-P0694"> 
	 <authcontrolarea> 
		<head>AUTHORITY CONTROL AREA</head> 
		<unitid label="Identity Code" encodinganalog="isaar11" type="NAHSTE"
		 repositorycode="0237">GB 0237 NAHSTE P0694</unitid> 
		<authentry encodinganalog="isaar13" label="Authority Entry"
		 authfilenumber="GB 0237 NAHSTE P0694" normal="Romanes, George John">Romanes |
		  George John | 1848-1894 | biologist</authentry> 
	 </authcontrolarea> 
	 <infoarea encodinganalog="isaar2"> 
		<head>INFORMATION AREA</head> 
		<occsphere encodinganalog="isaar226"> 
		  <head>Occupation, Sphere of Activity</head> 
		  <p>George John Romanes (<date type="life-span"
			 normal="1848/1894">1848-1894</date>), the eminent Darwinist scientist, was born
			 in Canada, but brought up in London. His childhood was dogged by ill health,
			 hampering his education, and he showed no early sign of his later brilliance.
			 He attended Gonville and Caius College, Cambridge, graduating in the second
			 class in 
			 <date type="single" normal="1870">1870</date>. Charles Darwin (<date
			 normal="1809/1882" type="life-span">1809-1882</date>) - a personal friend of
			 his - had substantial influence on the studies of Romanes. Despite early strong
			 religious beliefs, Romanes was converted to Darwinism, and wrote a critical
			 treatise on theism, under the pseudonym
			 <bibref><title>Physicus</title></bibref>. At the end of his life, he wrote a
			 second religious treatise, this time orthodox in belief, under the pseudonym of
			 <bibref><title>Metaphysicus</title></bibref>.</p> 
		  <p>Romanes' studies covered three related fields: physiology,
			 psychology and evolution. He conducted a number of experiments on the jellyfish
			 (medusa) in order to determine whether it has a nervous system. He also
			 co-operated with James Cossar Ewart (<date normal="1851/1933"
			 type="life-span">1851-1933</date>) and Sir Edward Sharpey
			 Sch&#x00C3;&#x00A4;fer (<date normal="1850/1935"
			 type="life-span">1850-1935</date>) on a number of his experiments. One of his
			 controversial conclusions was that mutual infertility is the cause, rather than
			 the effect, of separate evolution of species. His interest in psychology was
			 actually primarily an interest in animal psychology, on which he wrote a number
			 of works. His studies on this were considered, however, to be speculative and
			 anthropomorphic, and were rapidly superseded by better works. They were,
			 nonetheless, useful in starting debate on the subject.</p> 
		  <p>Romanes' childhood ill health caught up with him in later life, and
			 he moved to Oxford to escape the unhealthy atmosphere of London. He died there
			 in 
			 <date type="single" normal="1894">1894</date>.</p> 
		</occsphere> 
		<relships encodinganalog="isaar228"> 
		  <head>Relationships</head> 
		  <p>Romanes had a personal and professional friendship with Charles
			 Darwin, and a working relationship with James Cossar Ewart and Sir Edward
			 Sharpey Sch&#x00C3;&#x00A4;fer.</p> 
		</relships> 
		<otherinfo encodinganalog="isaar229"> 
		  <head>Other Significant Information</head> 
		  <p>Notable publications:</p> 
		  <p><bibref><title>Candid Examination of Theism</title>,<imprint>(<date
			 type="publication" normal="1878">1878</date>)</imprint></bibref></p> 
		  <p><bibref><title>Animal Intelligence</title>, <imprint>(<date
			 type="publication" normal="1881">1881</date>)</imprint></bibref></p> 
		  <p><bibref><title>Mental Evolution in Animals</title>, <imprint>(<date
			 type="publication" normal="1883">1883</date>)</imprint></bibref></p> 
		  <p><bibref><title>Mental Evolution in Man</title>, <imprint>(<date type="publication"
			 normal="1888">1888</date>)</imprint></bibref></p> 
		  <p><bibref><title>Darwin and After Darwin</title>, <imprint>(<date type="publication"
			 normal="1892">1892</date>)</imprint></bibref></p> 
		</otherinfo> 
		<honqual encodinganalog="nahste2210"> 
		  <head>Honours, Qualifications and Appointments</head> 
		  <p><date type="single" normal="1870">1870</date>: Batchelor of Arts
			 (BA), Gonville and Caius College, Cambridge</p> 
		  <p><date type="appointmentdate" normal="1879">1879</date>: Elected
			 Fellow of the Royal Society (FRS)</p> 
		  <p><date type="single" normal="1882">1882</date>: Awarded Honorary
			 Doctor of Law (LLD), University of Aberdeen</p> 
		  <p><date type="chairspan" normal="1886/1890">1886-1890</date>:
			 Appointed Professor at the University of Edinburgh</p> 
		  <p><date type="chairspan" normal="1888/1891">1888-1891</date>:
			 Appointed Fullerian Professor Physiology at the Royal Institution</p> 
		  <p><date type="single" normal="1891">1891</date>: Awarded Master of
			 Arts (MA), University of Oxford</p> 
		</honqual> 
	 </infoarea> 
	 <notearea encodinganalog="ISAAR3"> 
		<archnote encodinganalog="isaar31"> 
		  <head>Notes</head> 
		  <p>List of sources for the biographical information:</p> 
		  <p> <bibref>
			 <persname source="ncarules" normal="Gillispie, Charles C"
			  role="editor">Gillispie, Charles C</persname>, <title
			 render="italic">Dictionary of scientific biography, Vol. XI</title>, (<imprint>
			 <geogname source="lcsh" authfilenumber="483"
			  normal="New York (N.Y.), United States">New York </geogname>, 
			 <publisher>Scribner's</publisher>, 
			 <date type="publication" normal="1975"
			 certainty="certain">1975</date>)</imprint></bibref></p> 
		  <p><bibref>
			 <persname source="ncarules" normal="Lee, Sidney" role="editor">Lee,
			 Sidney</persname>, <title render="italic">Dictionary of National Biography, vol
			 XVIII</title>, (<imprint>
			 <geogname source="lcsh" authfilenumber="530"
			 normal="London (England)">London</geogname>, 
			 <publisher>Smith, Elder &amp; Co</publisher>, 
			 <date type="publication" normal="1909"
			 certainty="certain">1909</date>)</imprint></bibref></p> 
		  <p><bibref> <title>Concise Dictionary of National Biography,Vol.
			 III</title>, (<imprint><geogname source="lcsh" authfilenumber="532"
			 normal="London (England)">London (England)</geogname>, 
			 <publisher>Oxford University Press</publisher>, 
			 <date type="publication" normal="1992"
			 certainty="certain">1992</date>)</imprint></bibref></p> 
		</archnote> 
		<rules encodinganalog="isaar32"> 
		  <head>Rules or Conventions</head> 
		  <p>Authority record created according to the <bibref>
			 <corpname normal="National Council on Archives">National Council on
			 Archives</corpname> <title>Rules for the Construction of Personal, Place and
			 Corporate Names (NCA Rules)</title> <imprint> 
			 <date type="publication" normal="1997">1997</date></imprint></bibref>
			 and <bibref> <corpname normal="International Council on Archives">International
			 Council on Archives: Ad Hoc Committee on Descriptive Standards</corpname>
			 <title>International Standard Archival Authority Record for Corporate Bodies,
			 Persons and Families (ISAAR)CPF</title> <imprint> 
			 <date type="publication"
			 normal="1995">1995</date></imprint></bibref></p> 
		</rules> 
		<creationdate encodinganalog="isaar33"> 
		  <p>Personal name authority record compiled for the NAHSTE project by
			 <persname role="archivist" normal="Usher, Olivier">Olivier Usher</persname>,
			 Edinburgh University Library Department of Special Collections, 
			 <date type="single" normal="20020405">05 April
				2002</date></p></creationdate> 
	 </notearea> 
  </aar>
</isaarcpf>

=== UoEMainLibrary/archiveslib/source_docs/isaar/ROBSON.XML
<?xml version="1.0"?>
<!DOCTYPE isaarcpf SYSTEM "file:///C|/Program%20Files/SoftQuad/XMetaL%202/Rules/isaar.dtd">
<isaarcpf> 
  <aarheader audience="internal" langencoding="ISO 639"
	aarstatus="edited-full-draft"> 
	 <aarid source="GB-0237" type="FPI"> "-//Edinburgh University Library
		Special Collections Division :: Archival Authority Records//DOCUMENT GB 0237
		NAHSTE P1865 20020710//EN" </aarid> 
	 <filedesc> 
		<titlestmt> 
		  <titleproper>GB 0237 NAHSTE P1865</titleproper> 
		  <subtitle>Robson | JM | 1900-1982 | geneticist</subtitle> 
		  <author>Compiled for the NAHSTE project by Margaret Stewart, Edinburgh
			 University Library Special Collections Division, 10 July 2002</author> 
		</titlestmt> 
		<publicationstmt> 
		  <publisher>Edinburgh University Library Special Collections
			 Division</publisher> 
		  <address> 
			 <addressline>The University of Edinburgh</addressline> 
			 <addressline>George Square</addressline> 
			 <addressline>Edinburgh EH8 9LJ</addressline> 
			 <addressline>Scotland</addressline> 
			 <addressline>United Kingdom</addressline> 
		  </address> 
		  <date type="single" normal="20020703">10 July 2002</date> 
		</publicationstmt> 
	 </filedesc> 
	 <profiledesc> 
		<creation>XML generated using the ISAAR(CPF) DTD and XMetal template
		  prepared, as part of the NAHSTE project, in collaboration with the GASHE
		  project, by Sarah Higgins, Edinburgh University Library Special Collections
		  Division, 2001, with assistance from Pete Johnston, Lesley Richmond and Moira
		  Rankin, Glasgow University Archive Services. </creation> 
		<langusage> 
		  <language>EN</language> 
		</langusage> 
	 </profiledesc> 
	 <revisiondesc> 
		<list> 
		  <item>No revisions to date</item> 
		</list> 
	 </revisiondesc> 
  </aarheader> 
  <frontmatter> 
	 <titlepage> 
		<titleproper>GB 0237 NAHSTE P1865</titleproper> 
		<subtitle>Robson | JM | 1900-1982 | geneticist</subtitle> 
		<author>Compiled for the NAHSTE project by Margaret Stewart , Edinburgh
		  University Library Special Collections Division, 10 July 2002</author> 
		<publisher>Edinburgh University Library Special Collections
		  Division</publisher> 
		<date type="single" normal="20020710">10 July 2002</date> 
	 </titlepage> 
  </frontmatter> 
  <aar id="GB-0237-NAHSTE-P1865"> 
	 <authcontrolarea> 
		<head>AUTHORITY CONTROL AREA</head> 
		<unitid label="Identity Code" encodinganalog="isaar11" type="NAHSTE"
		 repositorycode="0237">GB 0237 NAHSTE P1865</unitid> 
		<authentry encodinganalog="isaar13" label="Authority Entry"
		 authfilenumber="GB 0237 NAHSTE P1865" normal="Robson, JM">Robson | JM |
		  1900-1982 | geneticist</authentry> 
	 </authcontrolarea> 
	 <infoarea encodinganalog="isaar2"> 
		<head>INFORMATION AREA</head> 
		<occsphere encodinganalog="isaar226"> 
		  <head>Occupation, Sphere of Activity</head> 
		  <p>J.M. Robson's pharmacological research paved the way for the
			 development of the contraceptive pill in the 
			 <date normal="1960/1969" type="inclusive"
			 certainty="uncertain">1960s</date>. </p>
		  <p>Robson was born in Belgium in 
			 <date normal="1900" type="single">1900</date>, but his family
			 (Rabinovitch), who were originally Russian, migrated to Leeds before World War
			 I. He attended school in Leeds and graduated from Leeds University in medicine
			 in 
			 <date normal="1925" type="single">1925</date>. There were no posts
			 available in physiological research that he had begun at Leeds so he accepted
			 an appointment at the Institute of Animal Breeding in Edinburgh in 
			 <date normal="1930" type="appointmentdate">1930</date>. Whilst there
			 he undertook research on the effects of gonadotrophins in pregnancy, and also
			 supervised the Pregnancy Diagnosis Station that had been founded by the
			 Institute's director Professor Francis Crew. </p>
		  <p>In 
			 <date normal="1932" type="appointmentdate">1932</date> he was
			 appointed lecturer at the Department of Pharmacology at the University of
			 Edinburgh, and thereafter pharmacology became his specialism, though he
			 maintained a strong interest in hormone research. In addition to studies of the
			 effects of hormones on the human uterus, he also worked on toxicology and
			 chemotherapy. In 
			 <date normal="1946" type="appointmentdate">1946</date> he was
			 appointed Reader in Pharmacology at Guy's Hospital Medical School, and was
			 Professor of Pharmacology there from 
			 <date normal="1950/1968" type="appointmentspan">1950-1968</date>,
			 when he retired.</p> 
		</occsphere> 
		<relships encodinganalog="isaar228"> 
		  <head>Relationships</head> 
		  <p>In the 
			 <date normal="1940/1949" type="inclusive">1940s</date> he
			 collaborated with Charlotte Auerbach (<date normal="1899/1994"
			 type="life-span">1899-1994</date>) on the causes of cell mutagenisis in fruit
			 flies (Drosophila) by mustard gas. He had first made the discovery that mustard
			 gas, like radiation, could cause cell mutagenisis in the 
			 <date normal="1930/1934" certainty="uncertain" type="inclusive">early
				1930s</date> whilst at the Institute of Animal Breeding in Edinburgh. His other
			 collaborators were: with Bertold Paul Wiesner, Marshall and George Bell on sex
			 hormones, with C.A. Keele on endocrinology, and with Marian on the chemistry of
			 steroids.</p> 
		</relships> 
		<otherinfo encodinganalog="isaar229"> 
		  <head>Other Significant Information</head> 
		  <p>By 1969 Robson estimated that he had published 259 scientific
			 papers. In addition to these he also published a number of monographs
			 including:<bibref><title>Recent Advances in Sex and Reproductive
			 Physiology</title>, ( <imprint><date type="publication"
			 normal="1934" certainty="certain">1934</date>)</imprint></bibref>
			 <bibref><title>Recent Advances in Pharmacology</title>, ( <imprint><date
			 type="publication" normal="1950"
			 certainty="certain">1950</date>)</imprint></bibref></p> 
		</otherinfo> 
		<honqual encodinganalog="nahste2210"> 
		  <head>Honours, Qualifications and Appointments</head>
		  <p>Held numerous appointments and honours amongst these are:</p> 
		  <p> 
			 <date normal="1932" type="single">1932</date>: Awarded D.Sc,
			 University of Edinburgh</p> 
		  <p><date normal="1968" type="appointmentdate">1968</date>: Appointed
			 Professor Emeritus, Guy's Hospital Medical School</p> 
		</honqual> 
	 </infoarea> 
	 <notearea encodinganalog="ISAAR3"> 
		<archnote encodinganalog="isaar31"> 
		  <head>Notes</head> 
		  <p>List of sources for the biographical information:</p> 
		  <p><bibref><persname source="ncarules" normal="Boyd, John Morton"
			 role="editor">James F. Crowe</persname> and
			 <persname source="ncarules" normal="Boyd, John Morton" role="editor">James F.
			 Dove </persname> (eds.)<title>Perspectives on Genetics: Anecdotal, Historical
			 and Critical Commentaries, 1987-1988</title>, ( <imprint>
			 <geogname source="lcsh" authfilenumber="511" normal="United States">United
			 States</geogname>, 
			 <date type="publication"
			  normal="1993">1993</date>)</imprint></bibref></p> 
		  <p><bibref><title>Who's Who 1978</title>, ( <imprint><geogname
			 source="lcsh" authfilenumber="499" normal="Great Britain">Great
			 Britain</geogname>, 
			 <publisher>A and C Black Ltd</publisher>, 
			 <date type="publication"
			 normal="1978">1978</date>)</imprint></bibref></p>
		</archnote> 
		<rules encodinganalog="isaar32"> 
		  <head>Rules or Conventions</head> 
		  <p>Authority record created according to the<bibref><corpname
			 normal="National Council on Archives">National Council on
			 Archives</corpname><title>Rules for the Construction of Personal, Place and
			 Corporate Names (NCA Rules)</title><imprint> 
			 <date type="publication" normal="1997">1997</date></imprint></bibref>
			 and <bibref><corpname normal="International Council on Archives">International
			 Council on Archives: Ad Hoc Committee on Descriptive
			 Standards</corpname><title>International Standard Archival Authority Record for
			 Corporate Bodies, Persona and Families (ISAAR)CPF</title><imprint> 
			 <date type="publication"
			 normal="1995">1995</date></imprint></bibref></p> 
		</rules> 
		<creationdate encodinganalog="isaar33"> 
		  <p>Personal name authority record compiled for the NAHSTE project by
			 <persname role="researcher" normal="Stewart, Margaret">Margaret
			 Stewart</persname>, Edinburgh University Library Special Collections Division, 
			 <date type="single" normal="20020710">10 July
				2002</date></p></creationdate> 
	 </notearea> 
  </aar>
</isaarcpf>
